export const GET_CATEGORIES = 'GET_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const SET_SELECTED_CATEGORIE = 'SET_SELECTED_CATEGORIE';
export const RECEIVE_DEMOGRAPHIC_DATA = 'RECEIVE_DEMOGRAPHIC_DATA';
export const REQUEST_DEMOGRAPHIC_DATA = 'REQUEST_DEMOGRAPHIC_DATA';
